micronaut:
  server:
    cors:
      enabled: true
  application:
    name: auditor-node
  router:
    static-resources:
      webui:
        paths: classpath:webui
        mapping: /webui/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
