version: "3.9"
services:
  ipfs-node:
    container_name: ipfs-node
    image: "ipfs/go-ipfs:v0.8.0"
    environment:
      IPFS_PROFILE: server
    ports:
      - "4001:4001"
      - "5001:5001"
    volumes:
      - ./ipfs-staging:/export
      - ./ipfs-data:/data/ipfs

  geth-node:
    container_name: geth-node
    image: "ethereum/client-go:v1.10.2"
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./geth:/root
      - ./geth-entrypoint.sh:/entrypoint.sh
      - ./geth-bootnodes:/bootnodes
