version: "3.9"
services:
  ipfs-node:
    container_name: ipfs-node
    image: "ipfs/go-ipfs:latest"
    environment:
      IPFS_PROFILE: server
    ports:
      - "4001:4001"
      - "5001:5001"
#      - "8080:8080" # if you want to expose IPFS gateway
    volumes:
      - ./ipfs-staging:/export
      - ./ipfs-data:/data/ipfs

  geth-node:
    container_name: geth-node
    image: "ethereum/client-go:latest"
    entrypoint: ["/entrypoint.sh"]
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./geth:/root
      - ./geth-entrypoint.sh:/entrypoint.sh
      - ./geth-bootnodes:/bootnodes
