# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Quality check

on: [pull_request]

jobs:
  code-control:
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Linter
        run: ./gradlew ktlinCheck
      - name: Code analysis
        run: ./gradlew detekt

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.0.0.2'
      - name: Check java binary
        run: java -version
      - name: Check gu
        run: |
          gu install native-image
          gu install espresso
          gu rebuild-images polyglot
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run all tests
        run: ./gradlew test
      - name: Generate test coverage report
        run: ./gradlew jacocoTestReport
      - name: Verify test coverage minimum limit
        run: ./gradlew jacocoTestCoverageVerification
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: build/reports/jacoco/report.xml
          fail_ci_if_error: false
